---
abstract: 'input and output messages from/to Syslog.'
author:
  - 'and COPYRIGHT'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Message::Passing::Syslog
name: Message-Passing-Syslog
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  JSON: 0
  Message::Passing: 0.104
  Moo: 0
  Parse::Syslog::Line: 1.2
  Sys::Hostname::Long: 0
  Task::Weaken: 0
  Time::ParseDate: 0
  Try::Tiny: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/suretec/Message-Passing-Syslog.git
version: 0.010
x_authority: cpan:GHENRY
